// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require("dotenv/config");

module.exports = {
  schema: "src/prisma/schema.prisma",
  migrations: {
    path: "src/prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
};
