// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require("dotenv/config");

module.exports = {
  schema: "src/prisma/schema.prisma",
  migrations: {
    path: "src/prisma/migrations",
  },
  datasource: {
    // Use a direct connection for Prisma CLI operations (migrations/introspection)
    // to avoid PgBouncer prepared statement issues.
    url: process.env.DIRECT_URL || process.env.DATABASE_URL,
  },
};
